-- ==========================================
-- College Database Assignment
-- Student Name:
-- Register No:
-- ==========================================

-- TODO:
-- 1. Create a database named CollegeDB
-- 2. Use the database
-- 3. Create a Department table with the following fields:
--
-- DepartmentID   Number(5)  Primary Key
-- DepartmentName Varchar(20)
-- HOD            Varchar(20)
--
-- Write your SQL below.
